# Generated by Django 4.1.7 on 2023-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CovidEffects', models.CharField(max_length=100)),
                ('OtherChallenges', models.CharField(max_length=100)),
                ('OtherChallengesSelected', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('ContactNumber', models.IntegerField(null=True)),
                ('EmailAddress', models.EmailField(blank=True, max_length=70, unique=True)),
                ('date', models.DateField(blank=True)),
                ('Officer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='generalParticulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=100)),
                ('Subcounty', models.CharField(max_length=100)),
                ('Building', models.CharField(max_length=100)),
                ('Floor', models.CharField(max_length=100)),
                ('Town', models.CharField(max_length=100)),
                ('Postaladdress', models.IntegerField(null=True)),
                ('Postalcode', models.IntegerField(null=True)),
                ('Telephone', models.IntegerField(null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('Institutioncategory', models.CharField(max_length=50)),
                ('InstitutionType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='outrunsGraduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=200)),
                ('CourseLevel', models.CharField(max_length=200)),
                ('CourseDuration', models.CharField(max_length=100)),
                ('ExaminingBody', models.CharField(max_length=200)),
                ('Year', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skillShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillArea', models.CharField(max_length=100)),
                ('SkilllevelRequired', models.CharField(max_length=100)),
                ('Optimal', models.CharField(max_length=100)),
                ('InPostGender', models.CharField(max_length=100)),
                ('ShortFall', models.CharField(max_length=200)),
                ('ReasonsForShortFall', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='staffTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberOfStaff', models.IntegerField(null=True)),
                ('NumberOfStaffWithDissability', models.IntegerField(null=True)),
                ('SkillArea', models.CharField(max_length=100)),
                ('SkillLevel', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='studentIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=100)),
                ('Courselevel', models.CharField(max_length=100)),
                ('Cost', models.IntegerField(null=True)),
                ('Intakeyear', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=50)),
            ],
        ),
    ]
