# Generated by Django 4.1.7 on 2023-03-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='EmailAddress',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='generalparticulars',
            name='Email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
