# Generated by Django 4.1.7 on 2023-03-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_challenges_emailaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalparticulars',
            name='Postaladdress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
