# Generated by Django 4.1.7 on 2023-03-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_generalparticulars_postaladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='challenges',
            name='Institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.institutions'),
        ),
        migrations.AddField(
            model_name='outrunsgraduates',
            name='Institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.institutions'),
        ),
        migrations.AddField(
            model_name='skillshortage',
            name='Institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.institutions'),
        ),
        migrations.AddField(
            model_name='studentintake',
            name='Institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.institutions'),
        ),
        migrations.AlterField(
            model_name='generalparticulars',
            name='Institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.institutions'),
        ),
    ]
