# Generated by Django 4.1.7 on 2023-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_institutions_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='Institution',
        ),
        migrations.RemoveField(
            model_name='outrunsgraduates',
            name='Institution',
        ),
        migrations.RemoveField(
            model_name='skillshortage',
            name='Institution',
        ),
        migrations.RemoveField(
            model_name='studentintake',
            name='Institution',
        ),
        migrations.AlterField(
            model_name='generalparticulars',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='institutions',
        ),
    ]
