# Generated by Django 4.1.7 on 2023-03-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_institution_challenges_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generalparticulars',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outrunsgraduates',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillshortage',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stafftotal',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentintake',
            name='Institution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
